# Generated by Django 2.2.1 on 2019-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('english_name', models.CharField(max_length=20)),
                ('card_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People_first',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('english_name', models.CharField(max_length=20)),
                ('card_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('english_name', models.CharField(max_length=20)),
                ('card_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People_third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('english_name', models.CharField(max_length=20)),
                ('card_id', models.IntegerField()),
            ],
        ),
    ]
